name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      logLevel:
        default: 'warning'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package
